# Generated by Django 5.0.2 on 2024-02-12 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comment_id_alter_reaction_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 2, 42, 40, 486039, tzinfo=datetime.timezone.utc)),
        ),
    ]
